server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: myalias
    key-password: password
  additional-tomcat-connectors: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #    properties:
    #      hibernate:
    #        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

      #  mail:
      #    host: localhost
      #    port: 1026
      #    username: username
      #    password: password
      #    properties:
      #      mail:
      #        smtp:
      #          trust: "*"
      #        auth: true
      #        starttls:
      #          enable: true
      #        connectiontimeout: 5000
      #        timeout: 3000
      #        writetimeout: 5000

    # for docker normal case
    mail:
      host: smtp.gmail.com
      port: 465
      username: adarshpandey12081999raj@gmail.com
      password: tmvj vmry uizl rdgq
      properties:
        mail:
          smtp:
            auth: true
            ssl:
              enable: true
              trust: "*"
          starttls:
            enable: true
      protocol: smtp

#  # for docker CI/CD
#  mail:
#    host: ${EMAIL_HOST_NAME}
#    port: 465
#    username: ${EMAIL_USER_NAME}
#    password: ${EMAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          ssl:
#            enable: true
#            trust: "*"
#        starttls:
#          enable: true
#    protocol: smtp

application:
  security:
    jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expiration: 8640000

  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

  # adding for CI/CD. input allowed list of ports or urls or ip
  cors:
    origins: http://localhost:4200,http://localhost:8080

  file:
    uploads:
      photos-output-path: ./uploads
