spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 20MB

springdoc:
  default-produces-media-type: application/json

server:
#  port: 8088
  servlet:
    context-path: /api/v1/
